name: Deploy Azure Function App and Code

on:
  push:
    branches:
      - main  # This triggers the workflow on every push to the main branch.

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Azure Resource Manager (ARM) Template Deployment
      uses: azure/arm-deploy@v1
      with:
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
        template-file: .github/workflows/template.json
        parameters-file: .github/workflows/parameters.json
        deployment-name: azure-function-deployment

  deploy-function-code:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure  # Ensures that this step runs after the infrastructure is deployed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTION_APP_NAME }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
